version: "3.9"
services:
  postgres:
    image: postgres:latest
    user: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    #volumes:
      #- db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8082
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
  flyway:
    image: flyway/flyway
    # postgres url schema: jdbc:postgresql://host:port/database
    command: -url=jdbc:postgresql://postgres:5432/postgres -user=postgres -password=postgres -locations=filesystem:/flyway/sql -connectRetries=10  migrate
    volumes:
      - ${PWD}/migrations/sql:/flyway/sql
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - default
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  rabbitmq:
    image: rabbitmq:3.11.9-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vojnic/efpractice2:psql2
    depends_on:
      - postgres
      - flyway
    ports:
      - "40000:40000"
    environment:
      - pUrl=postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
      - DB=postgres
      - PASSWORD=postgres
      - USER=postgres
      - PORT=5432
      - mUrl=mongodb://mongo:mongo@localhost:27017
      - LISTEN_ADDRESS=0.0.0.0:40000
      - KAFKA_BROKERS=127.0.0.1:9092
      - KAFKA_CLIENT_ID=my-client
    networks:
      - default