version: '3'
services:
  zk1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zk1
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:22888:23888;
    volumes:
      - ./kafka/zk1/data:/var/lib/zookeeper/data
      - ./kafka/zk1/log:/var/lib/zookeeper/log
  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    ports:
      - "19092:19092"
    depends_on:
      - zk1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.24:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.24:19092
    volumes:
      - ./kafka/kafka1/data:/var/lib/kafka/data